spring:
  application:
    name: workshop-be-sql

  datasource:
    url: jdbc:sqlserver://ip:port;databaseName=dbName;encrypt=true;trustServerCertificate=true
    username: username
    password: password
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.SQLServerDialect

server:
  port: 8080
